// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHdCsuOgaeQbHEL61h4n0sFQ_kd81Mlg',
    appId: '1:231897107967:web:8d8d8f73a35c1859512bca',
    messagingSenderId: '231897107967',
    projectId: 'titans-bjj-app',
    authDomain: 'titans-bjj-app.firebaseapp.com',
    databaseURL: 'https://titans-bjj-app-default-rtdb.firebaseio.com',
    storageBucket: 'titans-bjj-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHp9nIf9tUKLQ7LJzwZ6GjRky58-VgFd8',
    appId: '1:231897107967:android:dc35c310ad79b117512bca',
    messagingSenderId: '231897107967',
    projectId: 'titans-bjj-app',
    databaseURL: 'https://titans-bjj-app-default-rtdb.firebaseio.com',
    storageBucket: 'titans-bjj-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuWvRrCjsVzS6Yl6GONUaQOaGVj0weYNQ',
    appId: '1:231897107967:ios:2a576981943660ad512bca',
    messagingSenderId: '231897107967',
    projectId: 'titans-bjj-app',
    databaseURL: 'https://titans-bjj-app-default-rtdb.firebaseio.com',
    storageBucket: 'titans-bjj-app.firebasestorage.app',
    iosClientId: '231897107967-e7hfch0f7jm8df8jflso4fpq6tufsvsn.apps.googleusercontent.com',
    iosBundleId: 'com.titans.titansBjj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuWvRrCjsVzS6Yl6GONUaQOaGVj0weYNQ',
    appId: '1:231897107967:ios:2a576981943660ad512bca',
    messagingSenderId: '231897107967',
    projectId: 'titans-bjj-app',
    storageBucket: 'titans-bjj-app.firebasestorage.app',
    iosBundleId: 'com.titans.titansBjj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcHdCsuOgaeQbHEL61h4n0sFQ_kd81Mlg',
    appId: '1:231897107967:web:641256ef510708ee512bca',
    messagingSenderId: '231897107967',
    projectId: 'titans-bjj-app',
    authDomain: 'titans-bjj-app.firebaseapp.com',
    storageBucket: 'titans-bjj-app.firebasestorage.app',
  );
}